### ISSUE TITLE
Patrcial 脚本最后sign哪里好像不会不能修改参数

### ISSUE THREAD

**Issue by HHRAYLAM** [luzhenqian/web3-examples#6]
我改了config参数，但是sign的坐标没变

**Comment by luzhenqian** [comment]
可以把你的配置 json 放到 GitHub 吗？我帮你检查一下。

**Comment by HHRAYLAM** [comment]
我用的text，我等下用json试试
[config.txt](https://github.com/user-attachments/files/15543531/config.txt)
